SocialGouv/www

- src/data/members.json
pour l'affectaiton de Jasmine et Lucie
> correction drdjscs en drjscs

- src/composants/Layout.js
en attendant qu'elles exsitent
> Retrait du lien vers les CGU

- pages/fonctionnement-incubateur.js
correction mauvais copier/coller
> Ajout étape création de la startup

- src/data/news.js
> news: release emjpm 1.2

- src/data/startups.json
sur la fiche e-mjpm, ajout des liens vers la doc
> startups: ajout liens docs emjpm

- src/data/news.js
les balises qui sont dans le html des news n'apparaissent pas (ou, plus précisément, elles apparaissent puis disparaissent). Le quickfix fait la liste "à la main".
> Quick fix pb affichage

- src/composants/BlocChiffres.js
**BEFORE :**
**AFTER :**
\review @revolunet
> improv(bloc-chiffres): add some more space

- pages/actus.js
- pages/evenements.js
- pages/faq.js
- pages/fonctionnement-incubateur.js
- pages/index.js
- src/composants/Api.js
- src/composants/Article.js
- src/composants/BlocChiffres.js
- src/composants/EventBriteEvents.js
- src/composants/Header.js
- src/composants/Hero.js
- src/composants/LayoutArticle.js
- src/composants/Nav.js
- src/composants/Newsletter.js
- src/composants/Section.js
- src/composants/SectionCards.js
- src/composants/SectionColors.js
- src/custom.css
>  refacto(section): use new section class

- pages/actus.js
> Improv actus ensure that the actus cards are displayed

- src/data/news.js
> add news cdtn sprint 1.1

- src/data/startups.json
fix les liens du code du travail vers le repo principal
> fix(cdtn): fix github links

- pages/_document.js
- pages/_error.js
- pages/actus/board-juin-2018.js
- pages/actus/saison2.js
- pages/example.js
- pages/faq.js
- pages/index.js
- pages/startups/code-du-travail-numerique/index.mdx
- pages/startups/code-du-travail-numerique/kickoff.mdx
- pages/startups/code-du-travail-numerique/ux.mdx
- pages/startups/e-mjpm.mdx
- pages/startups/work-in-france.mdx
- src/composants/BlocChiffres.js
`’` is not `'`.
This was a tricky one...
I don't know from where it comes from...
> style: replace right single quotation mark by single quote

- pages/actus.js
- pages/actus/board-juin-2018.js
- pages/actus/saison2.js
- pages/faq.js
- pages/fonctionnement-incubateur.js
- pages/index.js
- src/composants/AllActus.js
- src/composants/Header.js
- src/composants/LayoutArticle.js
- src/composants/Nav.js
- src/composants/Notes.js
- src/composants/Section.js
- src/composants/SectionCards.js
> style: run eslint/prettier autofix

- pages/actus/board-juin-2018.js
- pages/faq.js
- pages/startups/code-du-travail-numerique/genese.mdx
- pages/startups/code-du-travail-numerique/ux.mdx
- src/data/news.js
> style: replace non-breaking space char by whitespace

- pages/_document.js
- pages/_error.js
- pages/actus/board-juin-2018.js
- pages/actus/saison2.js
- pages/example.js
- pages/faq.js
- pages/index.js
- pages/startups/code-du-travail-numerique/genese.mdx
- pages/startups/code-du-travail-numerique/index.mdx
- pages/startups/code-du-travail-numerique/kickoff.mdx
- pages/startups/code-du-travail-numerique/ux.mdx
- pages/startups/e-mjpm.mdx
- pages/startups/work-in-france.mdx
- src/composants/BlocChiffres.js
- src/data/news.js
> refacto: clean up eric weird hidden characters 

- pages/actus.js
- src/composants/Api.js
- src/composants/Article.js
- src/composants/AuthorPanel.js
- src/composants/BlocChiffres.js
- src/composants/Card.js
- src/composants/Footer.js
- src/composants/GenericLink.js
- src/composants/Header.js
- src/composants/Hero.js
- src/composants/Layout.js
- src/composants/LayoutArticle.js
- src/composants/LayoutCDTN.js
- src/composants/Member.js
- src/composants/Nav.js
- src/composants/Notes.js
- src/composants/Notifications.js
- src/composants/Section.js
- src/composants/SectionCards.js
> refacto: add prop types

- pages/faq.js
- pages/index.js
- src/composants/Api.js
- src/composants/AuthorPanel.js
- src/composants/Card.js
- src/composants/Footer.js
- src/composants/GenericLink.js
- src/composants/Header.js
- src/composants/Layout.js
- src/composants/LayoutCDTN.js
- src/composants/Nav.js
> style: resolve jsx-a11y/anchor-is-valid errors

- pages/_error.js
- pages/evenements.js
- src/composants/Footer.js
- src/composants/LayoutArticle.js
- src/composants/SectionCards.js
- src/composants/SvgIcons.js
> style: resolve react/display-name

- pages/_error.js
- pages/evenements.js
- src/composants/Footer.js
- src/composants/LayoutArticle.js
- src/composants/SectionCards.js
- src/composants/SvgIcons.js
Reverts SocialGouv/socialgouv.github.io#66
> Revert "style: resolve react/display-name"

- pages/_document.js
- pages/actus.js
- src/composants/GenericLink.js
- src/composants/Layout.js
- src/composants/LayoutArticle.js
- src/composants/Member.js
> styles: remove unused variables

- pages/actus/board-juin-2018.js
- pages/actus/saison2.js
> styles: add missing alt to images

- pages/actus/saison2.js
---
see https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-no-target-blank.md
> improv: add rel="noopener noreferrer" to target="_blank" links

- package.json
- src/composants/EventBriteEvents.js
- yarn.lock
> Style final touch

- src/data/news.js
> fix : Mise en forme de la brève sur emjpm

- pages/startups/domifacile.mdx
- src/composants/BlocChiffres.js
- src/data/members.json
- src/data/startups.json
et maj des indicateurs sur la page d'accueil en conséquence
> Ajout de la fiche produit "domiciliation"

- src/custom.css
fir crazy iframes, ex : https://socialgouv.github.io/actus/
> fix: prevent iframe overflow

- .travis.yml
> chore: make travis use yarn@1.13.0

- package.json
- pages/startups/code-du-travail-numerique/droit-libre.mdx
- src/composants/LayoutCDTN.js
- yarn.lock
> article droit-libre

- scripts/github-stats.js
fix race condition when repo with no activity
> fix: strip invalid repos

- scripts/github-stats.js
> hotfix2: commits

- pages/index.js
- src/composants/AsyncFetch.js
use AsyncFetch to always get the latest stats
> fix(gh-stats): use AsyncFetch to always get latest data

- .travis.yml
- static/github-stats.json
dont automate GH stats generation until it works :)
> fix: dont regenerate GH stats with travis

- src/composants/Layout.js
> style: remove commented code for no reason

- src/custom.css
> improv: center card cover images

- src/composants/Layout.js
> feat(layout): add link to members page in the header

- pages/members.js
> improv(members): add some top and bottom space

- pages/members.js
- src/composants/Card.js
- src/composants/Layout.js
- src/custom.css
> feat(members): add dedicated members page

- .gitlab-ci.yml
> ci: try gitlab ci

- .travis.yml
- scripts/github-stats.js
> feat: automated gh-stats update 🚀

- .travis.yml
> revert(cdedf96): use the mock

- .travis.yml
> fix: gh-stats again

- src/composants/Layout.js
@EricH34 : est-ce que l'inscription newsletter a déjà été utile ?
Si ce n'est pas le cas, je propose de supprimer ce bloc qui fait un hit gratuit chez google fonts
> fix: remove newsletter and associated tracker

- pages/_app.js
- pages/_document.js
- src/data/news.js
- src/github-highlight.css
Suppression cookies rawgit + dailymotion
> fix(RGPD): rm external cookies

- src/data/startups.json
nettoyage de urls des startups
> fix: cleanup

- .github/ISSUE_TEMPLATE/onboarding-dev.md
> Update issue templates

- pages/startups/code-du-travail-numerique/release-v3.2.0.mdx
- src/composants/LayoutCDTN.js
- src/data/news.js
> doc: add article CDTN v.3.2.0

- pages/startups/work-in-france.mdx
Ajout de la news sur les 10000 dossiers acceptés
> wif: add timeline 10000

- pages/index.js
> fix(home): simpler

- package.json
- pages/fonctionnement-incubateur.js
- src/composants/Section.js
- static/github-stats.json
- yarn.lock
Refresh page fonctionnement-incubateur
> feat: refresh page fonctionnement

- package.json
- scripts/github-stats.js
- yarn.lock
> feat: use graphQL for github-stats

- .github/ISSUE_TEMPLATE/onboarding-dev.md
> chore(onboarding): activate 2FA

- src/data/members.yml
Add Gary van Woerkens info to members file.
> Add gary.van-woerkens

- package.json
- pages/startups/code-du-travail-numerique/droit-libre.mdx
- pages/startups/code-du-travail-numerique/release-v3.2.0.mdx
- yarn.lock
> chore: remove react-youtube

- .github/ISSUE_TEMPLATE/offboarding.md
> feat: add offboarding issue

- src/composants/TimelineEvent.js
> fix(timeline): fix some timeline css

- .gitlab-ci.yml
- .k8s/components/www.ts
- .k8s/environments/.gitlab-ci.env
- .k8s/environments/_base/index.ts
- .k8s/environments/_base/www.ts
- .k8s/package.json
- .k8s/yarn.lock
- package.json
> build(k8s): use Kosko and beta pipeline

- pages/members.js
- src/data/members.yml
> feat(members): fade out if not here anymore

- .k8s/environments/prod/manifests/redirect.yaml
> fix(k8s): allow path in redirect

- src/data/startups.yml
> feat(startups): textstyle is no more

- src/data/startups.yml
> fix(startups): update wif stats link

- .gitlab-ci.yml
> docs(gitlab): remove old comment

- .k8s/__tests__/__snapshots__/kosko generate --env dev.ts.snap
- .k8s/__tests__/__snapshots__/kosko generate --env preprod.ts.snap
- .k8s/__tests__/__snapshots__/kosko generate --env prod.ts.snap
- .k8s/__tests__/kosko generate --env dev.ts
- .k8s/__tests__/kosko generate --env preprod.ts
- .k8s/__tests__/kosko generate --env prod.ts
> test(k8s): add missing HARBOR_PROJECT var env

- .gitlab-ci.yml
> ci(gitlab): adding kapp to the pipeline

- src/data/startups.yml
> feat(startups): end of Work In France

- src/data/startups.yml
Update github repo link (repo was moved).
> fix: update startup data tumeplay

- pages/startups/tumeplay.mdx
Mise à jour des informations pour la startup Tumeplay
> fix: update tumeplay.mdx informations

- pages/startups/dora.mdx
- src/composants/Footer.js
- src/composants/SectionCards.js
> fix: small fixes

- pages/index.js
- pages/mentions-legales.js
- pages/startups/work-in-france.mdx
- src/composants/Layout.js
- src/composants/SectionCards.js
- src/composants/TimelineEvent.js
- src/custom.css
- header : s/produits/startups
- home: séparation des SE en deux catégories
- ajout de la date de fin pour work in france
- rm opacité pour la startups terminées
https://www-small-fixes.dev.fabrique.social.gouv.fr/
> fix: some fixes

- pages/index.js
- src/composants/LayoutArticle.js
- src/data/startups.yml
Passage en "partenariat terminé" pour DORA, CDB, EMJPM, Medle
> fix: set partenariats terminés

- src/app/layout.tsx
- src/styles/globals.css
on fera le dark mode plus tard non ?
> feat: temporary force light mode
